"""Alembic environment. **Imports no implementation, and that is Plan 9 step 3.**

This tree used to live in `impl/claude-python/` and this file used to begin

    from agent_service.config import Settings
    from agent_spec.db.engine import normalize_url
    from agent_spec.db.models import Base

which made one implementation's ORM the AUTHORITY on a schema several
implementations share. `target_metadata = Base.metadata` is the line that did it:
`alembic revision --autogenerate` diffed the database against *those* models, so
the schema was decided wherever they were edited.

**The direction is now the one `spec/` already has with `impl/`:**

    schema/schema-<rev>.sql   the published DDL, authoritative
            ^ generated by
    impl/common/db/migrations/               this tree -- operator tooling
            v conformed to by
    each implementation's model layer

So a revision is **authored**, not autogenerated, and each build's models are
checked against the common tree rather than being the source of it.
`impl/claude-python/tests/test_migrations.py::test_the_migrations_and_the_models_agree`
is that check. It never touches this file's `target_metadata`: it migrates a
throwaway database to head and then diffs *its own* `Base.metadata` against what
is actually there. That is what keeps the arrow pointing the right way -- the
comparison is identical, the direction of authority is not.

**Being self-contained is not a purity exercise.** An operator running
`alembic upgrade head` against a database should not need any implementation's
package importable -- and after this change they do not: the three imports above
became `os.environ` and eight lines of string handling.

Departures from the generated template, all deliberate:

1. **The URL comes from the environment or `-x url=`, never from `alembic.ini`.**
   A second source of truth in the ini file is how migrations get run against the
   wrong database. `sqlalchemy.url` is left empty there on purpose.
2. **`compare_type=True`.** Off by default, which means a column type change
   autogenerates an EMPTY revision -- a silent no-op migration is worse than a
   noisy one. Kept even though autogenerate is no longer the authoring path,
   because `test_the_migrations_and_the_models_agree` runs the same comparison
   in the opposite direction and would otherwise miss a type drift.
3. **Logging setup is skippable, and never disables existing loggers.** Alembic's
   documented convention for programmatic callers; `test_migrations.py`
   calls `command.upgrade` IN-PROCESS, and the template's bare
   `fileConfig(...)` would reconfigure logging for the rest of the pytest
   process -- with `disable_existing_loggers` defaulting to True, silencing every
   logger already created. `test_api_logging.py` asserts on this service's
   logging, and would then pass or fail depending on file collection order.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

config = context.config

if config.config_file_name is not None and config.attributes.get("configure_logger", True):
    fileConfig(config.config_file_name, disable_existing_loggers=False)

#: **`None` by default, and that is the inversion.** With no metadata,
#: `alembic revision --autogenerate` produces an empty revision instead of
#: silently deriving the shared schema from whichever implementation happens to
#: be importable. A caller that legitimately wants the comparison -- the
#: conformance test -- passes its own through `config.attributes["target_metadata"]`.
target_metadata = config.attributes.get("target_metadata")

#: The driver this service connects with. Migrations run through the same async
#: engine as the service, so the URL has to name it.
_ASYNC_SCHEME = "postgresql+asyncpg://"


def _normalize_url(url: str) -> str:
    """Accept the URL people actually write, reject the ones that cannot work.

    **A copy of `agent_spec.db.engine.normalize_url`, on purpose.** Importing
    it is what this file stopped doing; eight lines duplicated is the price of a
    migration tree an operator can run without an implementation installed, and
    it is the right trade -- the two cannot drift in any way that matters,
    because a URL either names the asyncpg driver or does not.

    `postgresql://` and `postgres://` are upgraded rather than rejected: they are
    what every Postgres tool, password manager and cloud console hands you, and
    silently getting a sync driver inside an async service is a worse outcome
    than a rewrite.
    """
    if url.startswith(_ASYNC_SCHEME):
        return url
    for prefix in ("postgresql://", "postgres://"):
        if url.startswith(prefix):
            return _ASYNC_SCHEME + url[len(prefix) :]
    raise RuntimeError(
        f"expected a postgresql:// or {_ASYNC_SCHEME} URL, got {url.split('://')[0]}://"
    )


def _url() -> str:
    """Resolve the database URL, preferring an explicit `-x url=...`.

    The override exists for the test harness and for `ci.py`, which point
    migrations at a throwaway container rather than at whatever the environment
    names.

    **Read straight from `os.environ`, not through any `Settings` class.** The
    variable is the platform's -- every implementation reads the same name -- and
    a `.env` is deliberately NOT loaded here: a migration is an operator action
    against a named database, and picking up a developer's dotfile is how one
    gets applied to the wrong one.
    """
    override = context.get_x_argument(as_dictionary=True).get("url")
    if override:
        return _normalize_url(override)
    url = os.environ.get("AGENT_SERVICE_DATABASE_URL")
    if not url:
        raise RuntimeError(
            "no database configured: set AGENT_SERVICE_DATABASE_URL, or pass "
            "-x url=postgresql://... to alembic"
        )
    return _normalize_url(url)


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection, target_metadata=target_metadata, compare_type=True
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _url()
    connectable = async_engine_from_config(
        section, prefix="sqlalchemy.", poolclass=pool.NullPool
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
