"""initial schema: sessions, runs, events, transcript_entries

Revision ID: a5cf3bd007f9
Revises: 
Create Date: 2026-07-29 18:06:06.918348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5cf3bd007f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sdk_session_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('permission_mode', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('total_turns', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_sdk_session_id'), 'sessions', ['sdk_session_id'], unique=False)
    op.create_table('transcript_entries',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(length=256), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index('transcript_entries_dedup', 'transcript_entries', ['session_key', 'uuid'], unique=True, postgresql_where=sa.text('uuid IS NOT NULL'))
    op.create_index('transcript_entries_session', 'transcript_entries', ['session_key', 'seq'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('sdk_session_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('result_subtype', sa.String(length=64), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('terminal_reason', sa.String(length=64), nullable=True),
    sa.Column('limit_hit', sa.String(length=32), nullable=True),
    sa.Column('num_turns', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('duration_api_ms', sa.Integer(), nullable=True),
    sa.Column('api_error_status', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permission_denials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interrupted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timed_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('outcome_missing', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_sdk_session_id'), 'runs', ['sdk_session_id'], unique=False)
    op.create_index(op.f('ix_runs_session_id'), 'runs', ['session_id'], unique=False)
    op.create_index('runs_session_started', 'runs', ['session_id', 'started_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='events_run_seq_unique')
    )
    op.create_index('events_run_seq', 'events', ['run_id', 'seq'], unique=False)
    op.create_index('events_type', 'events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('events_type', table_name='events')
    op.drop_index('events_run_seq', table_name='events')
    op.drop_table('events')
    op.drop_index('runs_session_started', table_name='runs')
    op.drop_index(op.f('ix_runs_session_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_sdk_session_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index('transcript_entries_session', table_name='transcript_entries')
    op.drop_index('transcript_entries_dedup', table_name='transcript_entries', postgresql_where=sa.text('uuid IS NOT NULL'))
    op.drop_table('transcript_entries')
    op.drop_index(op.f('ix_sessions_sdk_session_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
