"""sessions.total_cost_usd becomes nullable

Revision ID: d3f9a0c15e27
Revises: b1e7c4a90d32
Create Date: 2026-08-08

**NULL IS NOT ZERO, AND THAT IS THE ENTIRE CHANGE.** The column was
`NUMERIC(12,6) DEFAULT '0' NOT NULL`, so a session nobody could price recorded
`0.000000` -- a figure indistinguishable from a session that genuinely cost
nothing. After this:

  * `0`    -- this build CAN price a turn, and the floor has not moved.
  * `NULL` -- this build cannot price a turn at all.

`SessionRecord.total_cost_usd` in the published interface document has drawn
exactly that distinction since 0.16.0: *"null means this build cannot price a
turn at all, which is not the same as 0.0. Some agent SDKs report token usage
and no monetary figure; such an implementation reports null here for every
session rather than a 0.0 that would read as free."* The API said it; the column
could not express it. This is the column catching up.

**Measured, and it is why this lands now rather than later.** The Codex SDK
reports no monetary figure anywhere -- `grep -ri "usd|cost"` over the installed
package returns one false positive and nothing else -- so every session of a
Codex build is unpriced for its whole life. That build does not persist yet.
Changing the column before it starts writing rows costs one revision; changing
it afterwards costs a revision plus a decision about what the accumulated zeros
meant.

**THE SERVER DEFAULT GOES TOO, and dropping it is the operative half.** A column
that is nullable but still defaults to `0` records `0` for every row nobody
prices, which is the state this revision exists to end. `NULL` has to be what an
unwritten value *is*, not merely what it *may* be.

## Existing rows are left exactly as they are

`0` is not rewritten to `NULL` on the way up. Those rows were written by a build
that can price turns, so their `0` already carries this revision's meaning --
the floor did not move. Converting them would be replacing a fact with a guess,
on the only data in the table that is not ambiguous.

## The downgrade backfills, and it has to

`NULL` cannot survive a return to `NOT NULL`, so downgrade writes `0` into every
null first. **That is lossy and it is not reversible**: a row that meant "cannot
be priced" comes back meaning "was not priced", and nothing afterwards can tell
which it was. Recorded here rather than discovered by whoever runs it -- the
alternative is a downgrade that fails partway through on a table with data in
it, which is worse.

## Authored, not autogenerated

The first revision written under Plan 9 step 3. `migrations/env.py` no longer
imports any implementation's models, so `--autogenerate` has no metadata to diff
against and produces an empty revision by design. A schema several
implementations share is not decided by whichever one happens to be importable;
`impl/claude-python/tests/test_migrations.py::test_the_migrations_and_the_models_agree`
checks that build's ORM against this tree afterwards, which is the same
comparison pointing the other way.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f9a0c15e27"
down_revision: Union[str, Sequence[str], None] = "b1e7c4a90d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: The column type, restated because `alter_column` needs `existing_type` to
#: render `ALTER COLUMN` on PostgreSQL without reflecting the table -- and
#: reflection is unavailable in `--sql` (offline) mode, which is how the
#: published DDL is generated.
_MONEY = sa.Numeric(12, 6)


def upgrade() -> None:
    # `server_default=None` DROPS the default. Alembic's sentinel for "leave it
    # alone" is `False`, not `None` -- verified against the installed version
    # (`AlterColumnOp.modify_server_default: Any = False`), because the two are
    # easy to confuse and getting it wrong here would silently keep writing 0.
    op.alter_column(
        "sessions",
        "total_cost_usd",
        existing_type=_MONEY,
        nullable=True,
        server_default=None,
        existing_server_default=sa.text("0"),
    )


def downgrade() -> None:
    # BEFORE the NOT NULL, or the ALTER fails on the first null row. Lossy on
    # purpose -- see the module docstring.
    op.execute("UPDATE sessions SET total_cost_usd = 0 WHERE total_cost_usd IS NULL")
    op.alter_column(
        "sessions",
        "total_cost_usd",
        existing_type=_MONEY,
        nullable=False,
        server_default=sa.text("0"),
    )
