"""Build the delivery bundles as Maven artifacts.

    uv run --no-project python .ci/bundle.py            # build into temp/bundle
    uv run --no-project python .ci/bundle.py --install  # ... and mvn install

**TWO artifacts, split by how the consumer uses them** -- their ask, and the
argument is theirs and it is right:

| Artifact | Carries | Their scope |
|---|---|---|
| `agent-service-openapi` | the OpenAPI documents | test-only; never ships in their image |
| `agent-service-database` | every revision's DDL | **executed** at boot; ships inside their image |

Those are different dependency scopes and one artifact cannot be both. The
cadence argument points the same way: bundled, a gemini-only document fix would
move a dependency carrying executable DDL, and they would re-verify a boot gate
for a change that touched no SQL.

## The two versions, and why they differ

`agent-service-openapi` tracks `spec/VERSION`, so quoting a field and naming a
version stay the same act.

`agent-service-database` **must not**, for exactly the reason above. Its version is
`1.<number of revisions>.0`: it moves when the DDL set changes and at no other
time. The number is a count and claims nothing semantic -- **the revision id is
the identity**, it is in every resource name, and `index.json` is the authority.

## `-SNAPSHOT`, in Maven's spelling

An in-flight `0.19.0-snapshot` is published as `0.19.0-SNAPSHOT`. Maven treats
only the uppercase suffix as mutable: it re-resolves rather than trusting a
cache, and refuses to let a release depend on one. Lowercase would be an
ordinary release version to every Maven client -- cached as immutable, never
re-resolved -- which would freeze, on the consumer's side, a document still being
written. Released versions plain, in-flight versions `-SNAPSHOT`. Both sides
reached this independently.

## `index.json`, and the one place this differs from what was asked

Each artifact carries an index **of its own contents**, rather than one index
describing both. A hash is worth having because it is checkable against bytes
that are present; an index in the spec jar vouching for DDL it does not contain
would be a claim nobody can verify from the artifact holding it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec"
OUT = ROOT / "temp" / "bundle"

GROUP_ID = "com.npf"
SPEC_ARTIFACT = "agent-service-openapi"
SCHEMA_ARTIFACT = "agent-service-database"

POM = """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by .ci/bundle.py. Do not edit: rebuild it. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 \
http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>{group}</groupId>
  <artifactId>{artifact}</artifactId>
  <version>{version}</version>
  <packaging>jar</packaging>

  <name>{name}</name>
  <description>{description}</description>

  <!-- NO DEPENDENCIES, deliberately. Anything declared here lands on the
       consumer's classpath and inside their runtime image; this artifact is
       resources and carries no code at all. -->

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <!-- The two ids are what a settings.xml <server> must match. Maven picks the
       target by the version suffix, not by anything written here: -SNAPSHOT
       goes to snapshotRepository and a bare version to repository, which is
       why the two must never point at the same Nexus repo. -->
  <distributionManagement>
    <repository>
      <id>{releases_id}</id>
      <url>{base}/repository/maven-releases/</url>
    </repository>
    <snapshotRepository>
      <id>{snapshots_id}</id>
      <url>{base}/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>
</project>
"""

# host.docker.internal rather than localhost, so the same coordinates resolve
# from a container as from this host -- localhost inside a container is the
# container. Override for a different Nexus; the path suffixes are Nexus's own.
NEXUS_BASE = "http://host.docker.internal:8081"
RELEASES_ID = "agent-service-nexus-releases"
SNAPSHOTS_ID = "agent-service-nexus-snapshots"


def render_pom(**fields: str) -> str:
    """The template plus the deploy targets, which are the same for both."""
    return POM.format(base=NEXUS_BASE, releases_id=RELEASES_ID,
                      snapshots_id=SNAPSHOTS_ID, **fields)


def maven_version(version: str) -> str:
    """`0.19.0-snapshot` -> `0.19.0-SNAPSHOT`. See the module docstring."""
    return re.sub(r"-snapshot$", "-SNAPSHOT", version)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def version_dir(version: str) -> Path:  # noqa: ARG001
    """**`spec/openapi/`**, since 2026-08-19 (user).

    There are no version directories any more: `spec/` carries exactly one
    version, and every version before it lives in its `release-<version>` git
    tag. **This script is meant to be run from a checkout of that tag** -- the
    release artifacts are built on the tag, so `spec/` is the release when it
    matters and the current snapshot otherwise.
    """
    return SPEC / "openapi"


def _write(resources: Path, target: str, source: Path) -> dict[str, str]:
    destination = resources / target
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    return {"path": f"/{target}", "sha256": sha256(source)}


def build_spec(version: str) -> tuple[Path, str]:
    """The documents, plus the prose a schema cannot carry."""
    maven = maven_version(version)
    project = OUT / SPEC_ARTIFACT
    resources = project / "src" / "main" / "resources"
    resources.mkdir(parents=True)

    source = version_dir(version)
    documents = sorted(source.glob("*.json"))
    if not documents:
        raise SystemExit(f"no documents at {source.relative_to(ROOT).as_posix()}/")

    entries: dict[str, dict[str, str]] = {}
    for doc in documents:
        target = f"agent-service/spec/{version}/{doc.name}"
        # `<what>-<version>.json` -> `<what>`: an implementation name,
        # or "core" for the intersection. One namespace, deliberately.
        key = doc.stem.removesuffix(f"-{version}")
        entries[key] = _write(resources, target, doc)

    index = {
        "artifact": f"{GROUP_ID}:{SPEC_ARTIFACT}:{maven}",
        "contains": ["documents"],
        "spec_version": version,
        "documents": {version: entries},
    }
    (resources / "agent-service").mkdir(parents=True, exist_ok=True)
    (resources / "agent-service" / "index.json").write_text(
        json.dumps(index, indent=2) + "\n", encoding="utf-8"
    )

    readme = (ROOT / ".ci" / "bundle-README.md").read_text(encoding="utf-8")
    readme = (readme.replace("{{VERSION}}", version)
                    .replace("{{MAVEN_VERSION}}", maven)
                    .replace("{{COORDINATES}}", f"{GROUP_ID}:{SPEC_ARTIFACT}:{maven}"))
    (resources / "agent-service" / "spec" / "README.md").write_text(readme, encoding="utf-8")

    (project / "pom.xml").write_text(render_pom(
        group=GROUP_ID, artifact=SPEC_ARTIFACT, version=maven,
        name="agent-service specification",
        description=("Every implementation's OpenAPI document and the structural "
                     "core they share. Resources only; no code, no dependencies."),
    ), encoding="utf-8")
    return project, maven


def build_schema(snapshot: bool = False) -> tuple[Path, str]:
    """**Every revision, not only the head.**

    Their requirement, and the reason is theirs: they create a schema and refuse
    to touch one at any other revision, so an operator mid-migration has to be
    able to name a revision that is not the newest.

    `snapshot` appends `-SNAPSHOT` and changes nothing else. It does **not**
    make this version track `spec/VERSION` -- the count is still the count, and
    the module docstring says why that separation is the consumer's own ask.
    What it buys is a mutable coordinate to publish before the DDL set is final,
    so a bare `1.n.0` is only ever written when it is meant to be permanent.
    """
    project = OUT / SCHEMA_ARTIFACT
    resources = project / "src" / "main" / "resources"
    resources.mkdir(parents=True)

    schemas = sorted((SPEC / "database").glob("agent-service-*.sql"))
    if not schemas:
        raise SystemExit("no DDL at spec/database/")

    entries: dict[str, dict[str, str]] = {}
    for sql in schemas:
        revision = sql.stem.removeprefix("agent-service-")
        entries[revision] = _write(resources, f"agent-service/schema/{sql.name}", sql)

    # See the module docstring: moves with the DDL set and at no other time.
    version = f"1.{len(schemas)}.0" + ("-SNAPSHOT" if snapshot else "")
    index = {
        "artifact": f"{GROUP_ID}:{SCHEMA_ARTIFACT}:{version}",
        "contains": ["schema"],
        # **Not "the latest".** Which revision a deployment should be at is a
        # property of the service it runs, not of this artifact.
        "schema": entries,
    }
    (resources / "agent-service").mkdir(parents=True, exist_ok=True)
    (resources / "agent-service" / "index.json").write_text(
        json.dumps(index, indent=2) + "\n", encoding="utf-8"
    )

    (project / "pom.xml").write_text(render_pom(
        group=GROUP_ID, artifact=SCHEMA_ARTIFACT, version=version,
        name="agent-service database schema",
        description=("The from-base DDL for every schema revision the "
                     "specification has shipped, named by revision. Resources "
                     "only; no code, no dependencies."),
    ), encoding="utf-8")
    return project, version


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the delivery bundles.")
    parser.add_argument("--install", action="store_true",
                        help="mvn install rather than mvn package")
    parser.add_argument("--deploy", action="store_true",
                        help="mvn deploy to Nexus. -SNAPSHOT only unless --release")
    parser.add_argument("--release", action="store_true",
                        help="permit --deploy to publish a bare version. ASK FIRST")
    parser.add_argument("--settings", default=None,
                        help="a settings.xml carrying the deploy credential")
    parser.add_argument("--schema-snapshot", action="store_true",
                        help="build agent-service-database as 1.n.0-SNAPSHOT")
    parser.add_argument("--version", default=None, help="defaults to spec/VERSION")
    args = parser.parse_args()
    version = args.version or (SPEC / "VERSION").read_text(encoding="utf-8").strip()

    if args.deploy and args.install:
        raise SystemExit("--deploy and --install are different goals; pick one")

    if OUT.exists():
        shutil.rmtree(OUT)
    goal = "deploy" if args.deploy else "install" if args.install else "package"

    for project, artifact_version in (build_spec(version),
                                      build_schema(args.schema_snapshot)):
        # A bare version in maven-releases can never be replaced, so publishing
        # one is the user's call and not a flag's. -SNAPSHOT is replaceable by
        # design and needs no such gate. The two artifacts version
        # independently, which is why this is decided per artifact rather than
        # once: agent-service-database is bare while the spec is in flight.
        # It still builds -- only the publish is withheld.
        artifact_goal = goal
        withheld = (args.deploy and not args.release
                    and not artifact_version.endswith("-SNAPSHOT"))
        if withheld:
            artifact_goal = "package"
        name = project.name
        print(f"\n  {GROUP_ID}:{name}:{artifact_version}")
        if withheld:
            print("    NOT PUBLISHING -- a bare version needs --release")
        resources = project / "src" / "main" / "resources"
        for path in sorted(resources.rglob("*")):
            if path.is_file():
                print(f"    {path.relative_to(resources).as_posix()}")
        command = ["mvn", "-q", "-B", artifact_goal]
        if args.settings:
            command[1:1] = ["-s", str(Path(args.settings).resolve())]
        result = subprocess.run(command, cwd=project,
                                shell=sys.platform == "win32")
        if result.returncode != 0:
            return result.returncode
        jar = project / "target" / f"{name}-{artifact_version}.jar"
        print(f"    -> {jar.relative_to(ROOT)}  ({jar.stat().st_size:,} bytes)")
        if artifact_goal == "deploy":
            print(f"    -> deployed to {NEXUS_BASE}")
    if args.install:
        print("\n  installed to the local repository")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
