-- agent-service -- PostgreSQL schema at Alembic revision b1e7c4a90d32
-- Generated by scripts/dump-schema.py from the Alembic revisions.
-- Do not edit; regenerate.

BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> a5cf3bd007f9

CREATE TABLE sessions (
    id VARCHAR(64) NOT NULL, 
    sdk_session_id VARCHAR(128), 
    title TEXT, 
    status VARCHAR(32) NOT NULL, 
    model VARCHAR(128), 
    permission_mode VARCHAR(32), 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    last_used_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    closed_at TIMESTAMP WITH TIME ZONE, 
    total_cost_usd NUMERIC(12, 6) DEFAULT '0' NOT NULL, 
    total_turns INTEGER DEFAULT '0' NOT NULL, 
    PRIMARY KEY (id)
);

CREATE INDEX ix_sessions_sdk_session_id ON sessions (sdk_session_id);

CREATE TABLE transcript_entries (
    seq BIGSERIAL NOT NULL, 
    session_key VARCHAR(256) NOT NULL, 
    uuid VARCHAR(128), 
    at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    entry JSONB NOT NULL, 
    PRIMARY KEY (seq)
);

CREATE UNIQUE INDEX transcript_entries_dedup ON transcript_entries (session_key, uuid) WHERE uuid IS NOT NULL;

CREATE INDEX transcript_entries_session ON transcript_entries (session_key, seq);

CREATE TABLE runs (
    id VARCHAR(64) NOT NULL, 
    session_id VARCHAR(64), 
    sdk_session_id VARCHAR(128), 
    started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    finished_at TIMESTAMP WITH TIME ZONE, 
    prompt TEXT NOT NULL, 
    result_text TEXT, 
    result_subtype VARCHAR(64), 
    stop_reason VARCHAR(64), 
    terminal_reason VARCHAR(64), 
    limit_hit VARCHAR(32), 
    num_turns INTEGER, 
    duration_ms INTEGER, 
    duration_api_ms INTEGER, 
    api_error_status INTEGER, 
    cost_usd NUMERIC(12, 6), 
    usage JSONB, 
    model_usage JSONB, 
    permission_denials JSONB, 
    errors JSONB, 
    is_error BOOLEAN, 
    error JSONB, 
    interrupted BOOLEAN DEFAULT 'false' NOT NULL, 
    timed_out BOOLEAN DEFAULT 'false' NOT NULL, 
    outcome_missing BOOLEAN DEFAULT 'false' NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(session_id) REFERENCES sessions (id) ON DELETE CASCADE
);

CREATE INDEX ix_runs_sdk_session_id ON runs (sdk_session_id);

CREATE INDEX ix_runs_session_id ON runs (session_id);

CREATE INDEX runs_session_started ON runs (session_id, started_at);

CREATE TABLE events (
    id BIGSERIAL NOT NULL, 
    run_id VARCHAR(64) NOT NULL, 
    seq INTEGER NOT NULL, 
    at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    type VARCHAR(32) NOT NULL, 
    subtype VARCHAR(64), 
    content JSONB, 
    raw JSONB, 
    PRIMARY KEY (id), 
    FOREIGN KEY(run_id) REFERENCES runs (id) ON DELETE CASCADE, 
    CONSTRAINT events_run_seq_unique UNIQUE (run_id, seq)
);

CREATE INDEX events_run_seq ON events (run_id, seq);

CREATE INDEX events_type ON events (type);

INSERT INTO alembic_version (version_num) VALUES ('a5cf3bd007f9') RETURNING alembic_version.version_num;

-- Running upgrade a5cf3bd007f9 -> b1e7c4a90d32

ALTER TABLE sessions ADD COLUMN agent_id VARCHAR(64);

CREATE INDEX ix_sessions_agent_id ON sessions (agent_id);

ALTER TABLE transcript_entries ADD COLUMN agent_id VARCHAR(64);

UPDATE alembic_version SET version_num='b1e7c4a90d32' WHERE alembic_version.version_num = 'a5cf3bd007f9';

COMMIT;

